import type { ChatService, TextDeltaHandler } from "../chat/chat-service.js";
import type {
  ApprovalBroker,
} from "../tools/approval-broker.js";
import type { ToolRegistry } from "../tools/tool-registry.js";
import type { ToolPolicyIdentity } from "../tools/tool-policy.js";
import type {
  SessionMetadata,
  SessionRecord,
  SessionStore,
} from "../session/session-store.js";

/** The capability profile is selected by a trusted host, not by user text. */
export type AgentSessionProfile = "read-only" | "web-workspace";

export interface AgentSessionDescriptor {
  /** Stable route key generated by a Channel Gateway. */
  sessionId: string;
  channel: string;
  conversationId: string;
  userId: string;
  /** Identity asserted by the entry point and consumed by Tool Policy. */
  identity: ToolPolicyIdentity;
  /** Tool capabilities fixed for the lifetime of the resident session. */
  profile?: AgentSessionProfile;
}

/** The small control surface AgentManager needs for lifecycle management. */
export interface AgentControl {
  abort(): void;
  waitForIdle(): Promise<void>;
}

/** A per-session runtime assembled by the application layer. */
export interface AgentSessionRuntime {
  readonly agent: AgentControl;
  readonly chat: Pick<ChatService, "send" | "reset">;
  /** Exposed for trusted host wiring and diagnostics, not for prompt execution. */
  readonly toolRegistry?: ToolRegistry;
}

export type AgentSessionFactory = (
  descriptor: Required<AgentSessionDescriptor>,
  session: SessionRecord,
) => AgentSessionRuntime | Promise<AgentSessionRuntime>;

export interface AgentSessionHandle {
  readonly session: SessionRecord;
  readonly descriptor: Required<AgentSessionDescriptor>;
  readonly toolRegistry?: ToolRegistry;
  send(text: string, onTextDelta: TextDeltaHandler): Promise<void>;
  reset(): Promise<void>;
  abort(): void;
}

export interface AgentManagerOptions {
  /** One shared persistence owner for all sessions managed by this process. */
  readonly sessionStore: SessionStore;
  /** One shared approval broker so approval events cross session boundaries safely. */
  readonly approvalBroker: ApprovalBroker;
  /** Model persisted on newly created session records by this manager. */
  readonly model?: string | null;
  /** Creates only the per-session Agent/ChatService/tool binding. */
  readonly createSession: AgentSessionFactory;
  /** Closes shared resources after all resident sessions become idle. */
  readonly closeResources?: () => Promise<void>;
}

export class AgentManagerClosedError extends Error {
  constructor() {
    super("AgentManager 已关闭。");
    this.name = "AgentManagerClosedError";
  }
}

export class AgentSessionBindingError extends Error {
  constructor(sessionId: string) {
    super(`会话 ${sessionId} 的渠道、用户、身份或工具能力绑定不一致。`);
    this.name = "AgentSessionBindingError";
  }
}

type SessionEntry = {
  readonly descriptor: Required<AgentSessionDescriptor>;
  readonly session: SessionRecord;
  readonly runtime: AgentSessionRuntime;
  queueTail: Promise<void>;
  closed: boolean;
};

/**
 * Process-local coordinator for resident Agents.
 *
 * The manager deliberately keeps persistence and approval resources outside the
 * session map. Opening one SQLite store per session would create a new approval
 * owner each time and could expire another session's pending approval.
 */
export class AgentManager {
  readonly sessionStore: SessionStore;
  readonly approvalBroker: ApprovalBroker;

  private readonly model: string | null | undefined;
  private readonly createSession: AgentSessionFactory;
  private readonly closeResources: () => Promise<void>;
  private readonly entries = new Map<string, SessionEntry>();
  private readonly initializations = new Map<
    string,
    Promise<SessionEntry>
  >();
  private closed = false;
  private closePromise: Promise<void> | undefined;

  constructor(options: AgentManagerOptions) {
    this.sessionStore = options.sessionStore;
    this.approvalBroker = options.approvalBroker;
    this.model = options.model;
    this.createSession = options.createSession;
    this.closeResources = options.closeResources ?? (async () => undefined);
  }

  /**
   * Return the resident session or initialize it exactly once for this key.
   * Concurrent first requests share the same initialization promise, so two
   * Agents can never race to restore and append the same session history.
   */
  async getOrCreate(
    input: AgentSessionDescriptor,
  ): Promise<AgentSessionHandle> {
    const descriptor = normalizeDescriptor(input);
    this.assertOpen();

    const existing = this.entries.get(descriptor.sessionId);
    if (existing) {
      assertBinding(existing.descriptor, descriptor, existing.session);
      return this.createHandle(existing);
    }

    const pending = this.initializations.get(descriptor.sessionId);
    if (pending) {
      const entry = await pending;
      this.assertOpen();
      assertBinding(entry.descriptor, descriptor, entry.session);
      return this.createHandle(entry);
    }

    const initialization = this.initialize(descriptor);
    this.initializations.set(descriptor.sessionId, initialization);
    try {
      const entry = await initialization;
      this.assertOpen();
      return this.createHandle(entry);
    } finally {
      if (this.initializations.get(descriptor.sessionId) === initialization) {
        this.initializations.delete(descriptor.sessionId);
      }
    }
  }

  /** Look up only a resident session; this method never opens a database session. */
  get(sessionId: string): AgentSessionHandle | undefined {
    if (this.closed) return undefined;
    const entry = this.entries.get(sessionId);
    return entry ? this.createHandle(entry) : undefined;
  }

  /**
   * Stop accepting work, abort active Agents, drain persistence, then close the
   * single shared Broker and SessionStore. The operation is idempotent.
   */
  async close(): Promise<void> {
    if (!this.closePromise) {
      this.closePromise = this.closeInternal();
    }
    return this.closePromise;
  }

  private async initialize(
    descriptor: Required<AgentSessionDescriptor>,
  ): Promise<SessionEntry> {
    const metadata: SessionMetadata = {
      conversationId: descriptor.conversationId,
      channel: descriptor.channel,
      userId: descriptor.userId,
      model: this.model,
    };
    const session = await this.sessionStore.getOrCreate(
      descriptor.sessionId,
      metadata,
    );
    assertSessionRecordBinding(descriptor, session);

    const runtime = await this.createSession(descriptor, session);
    if (this.closed) {
      await disposeRuntime(runtime);
      throw new AgentManagerClosedError();
    }

    const entry: SessionEntry = {
      descriptor,
      session: Object.freeze({ ...session }),
      runtime,
      queueTail: Promise.resolve(),
      closed: false,
    };
    this.entries.set(descriptor.sessionId, entry);
    return entry;
  }

  private createHandle(entry: SessionEntry): AgentSessionHandle {
    return {
      session: entry.session,
      descriptor: entry.descriptor,
      toolRegistry: entry.runtime.toolRegistry,
      send: (text, onTextDelta) =>
        this.enqueue(entry, () => entry.runtime.chat.send(text, onTextDelta)),
      reset: () => this.enqueue(entry, () => entry.runtime.chat.reset()),
      abort: () => entry.runtime.agent.abort(),
    };
  }

  private enqueue<T>(
    entry: SessionEntry,
    operation: () => Promise<T>,
  ): Promise<T> {
    // Keep the public send/reset surface promise-based even after shutdown; a
    // caller can therefore handle closure with the same rejection path as a
    // failed turn rather than catching a synchronous throw.
    if (this.closed || entry.closed) {
      return Promise.reject(new AgentManagerClosedError());
    }

    // Always settle queueTail itself, while returning the original result to the
    // caller. A failed turn must not permanently block later turns in the same
    // session.
    const next = entry.queueTail.then(
      () => this.runEntryOperation(entry, operation),
      () => this.runEntryOperation(entry, operation),
    );
    entry.queueTail = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  private async runEntryOperation<T>(
    entry: SessionEntry,
    operation: () => Promise<T>,
  ): Promise<T> {
    if (this.closed || entry.closed) throw new AgentManagerClosedError();
    try {
      return await operation();
    } finally {
      // The queue itself is the serialization state. Keeping this finally block
      // explicit documents that all ChatService persistence has settled before
      // the next operation starts.
    }
  }

  private async closeInternal(): Promise<void> {
    this.closed = true;

    // An initialization may still be restoring context. Wait for it before
    // closing SQLite; initialize() disposes a runtime created after close began.
    const initializations = [...this.initializations.values()];
    await Promise.allSettled(initializations);

    const entries = [...this.entries.values()];
    for (const entry of entries) {
      entry.closed = true;
      entry.runtime.agent.abort();
    }

    // queueTail resolves only after ChatService's finally block has persisted the
    // current Agent transcript, so shared resources can now be closed safely.
    await Promise.all(entries.map((entry) => entry.queueTail));
    await Promise.all(entries.map((entry) => entry.runtime.agent.waitForIdle()));
    this.entries.clear();
    await this.closeResources();
  }

  private assertOpen(): void {
    if (this.closed) throw new AgentManagerClosedError();
  }
}

function normalizeDescriptor(
  input: AgentSessionDescriptor,
): Required<AgentSessionDescriptor> {
  if (!input || typeof input !== "object") {
    throw new TypeError("AgentSessionDescriptor 格式无效。");
  }

  const sessionId = requiredText(input.sessionId, "sessionId");
  const channel = requiredText(input.channel, "channel");
  const conversationId = requiredText(input.conversationId, "conversationId");
  const userId = requiredText(input.userId, "userId");
  if (
    !input.identity ||
    typeof input.identity.authenticated !== "boolean"
  ) {
    throw new TypeError("AgentSessionDescriptor.identity 格式无效。");
  }

  const profile = input.profile ?? "read-only";
  if (profile !== "read-only" && profile !== "web-workspace") {
    throw new TypeError(`未知的 Agent 工具能力配置：${String(profile)}。`);
  }

  return Object.freeze({
    sessionId,
    channel,
    conversationId,
    userId,
    identity: Object.freeze({
      authenticated: input.identity.authenticated,
    }),
    profile,
  });
}

function assertBinding(
  expected: Required<AgentSessionDescriptor>,
  actual: Required<AgentSessionDescriptor>,
  session: SessionRecord,
): void {
  if (
    !sameDescriptorBinding(expected, actual) ||
    !sameSessionRecordBinding(expected, session)
  ) {
    throw new AgentSessionBindingError(expected.sessionId);
  }
}

function assertSessionRecordBinding(
  descriptor: Required<AgentSessionDescriptor>,
  session: SessionRecord,
): void {
  if (!sameSessionRecordBinding(descriptor, session)) {
    throw new AgentSessionBindingError(descriptor.sessionId);
  }
}

function sameDescriptorBinding(
  left: Required<AgentSessionDescriptor>,
  right: Required<AgentSessionDescriptor>,
): boolean {
  return (
    left.sessionId === right.sessionId &&
    left.channel === right.channel &&
    left.conversationId === right.conversationId &&
    left.userId === right.userId &&
    left.identity.authenticated === right.identity.authenticated &&
    left.profile === right.profile
  );
}

function sameSessionRecordBinding(
  descriptor: Required<AgentSessionDescriptor>,
  session: SessionRecord,
): boolean {
  return (
    session.id === descriptor.sessionId &&
    session.channel === descriptor.channel &&
    session.conversationId === descriptor.conversationId &&
    session.userId === descriptor.userId
  );
}

function requiredText(value: unknown, name: string): string {
  if (typeof value !== "string" || value.trim() === "") {
    throw new TypeError(`${name} 必须是非空字符串。`);
  }
  return value.trim();
}

async function disposeRuntime(runtime: AgentSessionRuntime): Promise<void> {
  runtime.agent.abort();
  await runtime.agent.waitForIdle().catch(() => undefined);
}
